### ISSUE TITLE
Fantomas' package name changed from `fantomas-tool` to `fantomas`

### ISSUE THREAD

**Issue by bddckr** [fsprojects/fantomas-for-vs#31]
Context: fsprojects/fantomas#2174

These lines should probably be changed to adhere to the rename:
https://github.com/fsprojects/fantomas-for-vs/blob/e77d68151347e028dbcbd981cee17e2654d93523/src/FantomasVs.Shared/FantomasHandler.cs#L355-L356

That way, the original intention by @nojaf is carried on to this Visual Studio extension as well: New users should be less confused. Suppose this change is not done to the VS extension. In that case, users might still get confused moving forward, as the extension adds a package to their machine (or local tools manifest) that is obsolete.

I see one issue with just changing it, though: `fantomas` is only a CLI tool starting in 5.0.0-alpha-003. Is it enough for this extension to wait for version 5 to be out of preview, perhaps? That way the `tool install` commands above would automatically pick a version that is at least the release version of v5.

**Comment by nojaf** [comment]
Yeah, right now you need to add `--prerelease` to install `fantomas`.
You could wait for v5 to be stable to update this, or move ahead with `--prerelease`.

**Comment by deviousasti** [comment]
This is only if if you don't have it already installed globally.
When `5.0` is released, I'll update this in the tool.

**Comment by Balinth** [comment]
> 



> This is only if if you don't have it already installed globally. When `5.0` is released, I'll update this in the tool.

Just pinging you that Fantomas 5.x is released.
