### ISSUE TITLE
fsharp_multiline_bracket_style setting is not applied

### ISSUE THREAD

**Issue by snuup** [fsprojects/fantomas-for-vs#47]
The Fantomas setting

    fsharp_multiline_bracket_style

is ignored. Why?

**Comment by nojaf** [comment]
What version are you on?

**Comment by deviousasti** [comment]
@nojaf maybe we should log the client version on start-up?

**Comment by nojaf** [comment]
You can get the version based on a file, different files could return different versions.
Which one will you log then?

Overall, @snuup should provide more details here. Otherwise, there is not enough to go on.

**Comment by deviousasti** [comment]
Good point.

**Comment by deviousasti** [comment]
@snuup If you're not sure how to get the version -
if you introduce a syntax error in your file and format, it should log the current version in the log.
![image](https://user-images.githubusercontent.com/2375486/231428097-c9012df9-ecb5-4642-bf4a-08203f729815.png)

**Comment by snuup** [comment]
Thank you so much, sry for the late reaction.

I am on "4.7.7" (great tip above, thx)

**Comment by nojaf** [comment]
That setting was only introduced in v5.2
See https://fsprojects.github.io/fantomas/docs/end-users/UpgradeGuide.html

**Comment by snuup** [comment]
Is it possible to use a later version with the Visual Studio extension?

I just updated fantomas this way:

dotnet tool update fantomas-tool -g
Tool 'fantomas-tool' was reinstalled with the latest stable version (version '4.7.9').

which gives me a too old version. How can I get version 5.2 or later?

**Comment by dawedawe** [comment]
@snuup The tool was renamed to just `fantomas`, see the details of v5 [here](https://fsprojects.github.io/fantomas/docs/end-users/UpgradeGuide.html).
So uninstall `fantomas-tool` and install `fantomas`.
